---
title: Digital Justice Lab
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/images
  values:
    image: true
name: Digital Justice Lab
markdown: kramdown
sass:
  style: compressed
