---
title: Digital Justice Lab
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Digital Justice Lab
markdown: kramdown
sass:
  style: compressed
footer:
- label: Contact Us
  url: mailto:hello@digitaljusticelab.ca
homepage_menu_items:
- url: "#about-us"
  title: About Us
- url: "#who-we-are"
  title: Who We Are
- url: "#what-we-do"
  title: What We Do
